-- Database: yayasan_db

CREATE DATABASE IF NOT EXISTS yayasan_db;
USE yayasan_db;

-- Users table for admin login
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

-- Pages table for Tentang, Yayasan, etc.
CREATE TABLE IF NOT EXISTS pages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
);

-- Struktur table for organization structure image and description
CREATE TABLE IF NOT EXISTS struktur (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_path VARCHAR(255) NOT NULL,
  description TEXT
);

-- Berita table for news
CREATE TABLE IF NOT EXISTS berita (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  date DATE NOT NULL
);

-- Insert default admin user (password: admin123)
INSERT INTO users (username, password_hash) VALUES (
  'admin',
  -- Password hash generated by PHP password_hash('admin123', PASSWORD_DEFAULT)
  '$2y$10$e0NRzQ6q6v6Q0v6Q0v6QOe0NRzQ6q6v6Q0v6Q0v6Q0v6Q0v6Q0v6Q'
);

-- Insert default pages
INSERT INTO pages (slug, title, content) VALUES
('tentang', 'Tentang Kami', 'Isi halaman Tentang Kami...'),
('yayasan', 'Yayasan', 'Isi halaman Yayasan...'),
('struktur', 'Struktur Organisasi', 'Deskripsi struktur organisasi...');

-- Insert default struktur image
INSERT INTO struktur (image_path, description) VALUES
('assets/images/struktur.jpg', 'Struktur organisasi yayasan');

-- Insert sample berita
INSERT INTO berita (title, content, date) VALUES
('Berita Pertama', 'Isi berita pertama...', '2024-01-01'),
('Berita Kedua', 'Isi berita kedua...', '2024-02-01');
